name: flutter_mvvm_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.2
  hooks_riverpod: ^2.4.2
  riverpod_annotation: ^2.1.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  go_router: ^13.2.1
  qr_flutter: ^4.1.0
  device_info_plus: ^9.0.3
  crypto: ^3.0.3
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  flutter_native_splash: ^2.3.3
  url_launcher: ^6.1.14
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.1
  meta: ^1.11.0
  firebase_core: ^2.1.7
  webview_flutter: ^4.4.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
